# Generated by Django 4.2.11 on 2024-07-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_item_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='occupation',
            new_name='father_occupation',
        ),
        migrations.AddField(
            model_name='item',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
